config/routes.rb
Rails.application.routes.prepend  do
  get "/themes/:key/image.png", :to => "refinery/themes/theme#screenshot"
  get "/themes/assets/:mime_type/*file_path", :to => "refinery/themes/theme#asset"
end

Refinery::Core::Engine.routes.prepend do
  # Admin routes
  namespace :themes, :path => '' do
    namespace :admin, :path => 'refinery' do
      scope :path => 'themes' do
        resource :editor, :controller => 'editor' do
          member do
            get :index
          end

          collection do
            post :list
            post :file
            post :save_file
            post :add
            post :rename
            post :delete
            post :upload
            get  :upload_file
          end
        end
      end


      resources :themes, :except => [:show, :destroy, :new] do
        collection do
          get :upload
          get :reset
          get :settings
          get :select_theme
        end
      end

    end
  end

end

app/models/refinery/themes/theme.rb
require 'open-uri'

module Refinery
  module Themes
    class Theme < Refinery::Core::BaseModel

      def default_assigns(str)
        yaml = YAML::load(str)["assigns"] || false
        return {} unless yaml
        assigns = extract_assigns(yaml, :vars)
        extract_assigns(yaml, :collections).each do |k, v|
          assigns[k] = Collection.find_by_key v
        end
        return assigns
      end


      class << self
        include ActionController::DataStreaming

        attr_accessor :content_type, :headers

        def current_theme_key
          ::Refinery::Setting.find_or_set(:current_theme, "default") if ActiveRecord::Base.connection.table_exists? 'refinery_settings'
        end

        def current_theme_config
          config_for(current_theme_key)
        end

        def default_layout
          ::Refinery::Setting.find_or_set(:default_layout, "site") if ActiveRecord::Base.connection.table_exists? 'refinery_settings'
        end

        def theme_path(theme_dir=current_theme_key)
          Rails.root.join("themes/#{theme_dir}")
        end

        def layout_raw(file_name)
          File.read(theme_path.join("layouts/#{file_name}.*.liquid"))
        end

        def all
          Dir.glob(Rails.root.join("themes", "*")).collect { |dir|
            config_for(dir.split("/").last)
          }
        end

        def config_for(key)
          YAML::load(File.open(theme_path(key).join("config/config.yml")))
        end

        def layouts
          layouts_list(theme_path.join("views/layouts/", "**/*.liquid"))
        end

        def templates
          templates_list(theme_path.join("views/refinery/pages/", "**/*.liquid"))
        end

        private

        def layouts_list(path)
          Dir.glob(path).collect { |file|
            file.split("/").last.gsub(/.liquid/, "")
          }
        end

        def templates_list(path)
          Dir.glob(path).collect { |file|
            file =~ /.*refinery\/pages\/(.*\.liquid)/
            $1
          }
        end

      end
    end
  end
end

app/controllers/refinery/themes/admin/editor_controller.rb
module Refinery
  module Themes
    module Admin
      class EditorController < ::Refinery::AdminController

        def index; end

        def upload_file
          @path = params[:path]
        end

        def upload
          file = params[:file]

          unless FileManager.allowed_content_type?(File.extname(file.original_filename))
            notice = 'File "%s" could not be uploaded' % File.extname(file.original_filename)
          else
            file_path = "#{params[:path]}/#{file.original_filename}"
            FileManager.save_file(file_path, file.read)
            notice = "A new file was successfully uploaded!"
          end
          @dialog_successful = true
          render :nothing => true, :layout => 'refinery/admin_dialog'
          #render :action => 'index'
          #redirect_to(refinery.root_themes_admin_editor_path, :notice => notice)
        end

        def list
          @parent = params[:fullpath]
          file_manager = FileManager.new(Rails.root.join("themes/#{Refinery::Themes::Theme.current_theme_key}/#{@parent}"), @parent)
          render :json => file_manager.dirs.concat(file_manager.files), :layout => false
        end

        def file
          @related_path = params[:fullpath]
          file = File.join(Rails.root, "themes", Refinery::Themes::Theme.current_theme_key, params[:fullpath])
          render :text => 'file not found' and return unless File.exist? file
          @content = File.read(file)
          @content_type = Editable.mime_for file

          if @content_type == 'image'
            render :inline => "<%= image_tag '#{params[:fullpath]}' %>"
          else
            render :layout => false
          end
        end

        def save_file
          @related_path = params[:file_name]
          @content = FileManager.save_file(@related_path, params[:file_content])
          @content_type = Editable.mime_for @related_path
          render :template => 'refinery/themes/admin/editor/file.html.erb', :layout => false
        end

        def add
          render(:json => FileManager.create_dir(params[:fullpath], params[:title]), :layout => false) if params[:type].eql?('folder')
          render(:json => FileManager.create_file(params[:fullpath], params[:title]), :layout => false) if params[:type].eql?('default')
        end

        def rename
          render(:json => FileManager.rename_dir(params[:fullpath], params[:new_name]), :layout => false) if params[:type].eql?('folder')
          render(:json => FileManager.rename_file(params[:fullpath], params[:new_name]), :layout => false) if params[:type].eql?('default')
        end

        def delete
          render(:json => FileManager.remove_dir(params[:fullpath]), :layout => false) if params[:type].eql?('folder')
          render(:json => FileManager.remove_file(params[:fullpath]), :layout => false) if params[:type].eql?('default')
        end

      end
    end
  end
end

app/controllers/refinery/themes/admin/themes_controller.rb
require 'sprockets'

module Refinery
  module Themes
    module Admin
      class ThemesController < ::Refinery::AdminController

        def index
          @themes = Refinery::Themes::Theme.all
        end

        def upload; end

        def settings; end

        def update

        end

        def reset
          FileUtils.rm_rf(Rails.root.join('themes', 'default')) if File.exist?(Rails.root.join('themes', 'default'))
          FileManager.unzip_theme(File.join(Refinery::Themes::Engine.root, "theme_template", "default.zip"))
          redirect_to themes_admin_root_url, :notice =>"The default theme successfully reset!"
        end

        def select_theme
          return unless params[:key]

          FileUtils.rm_rf(Rails.root.join('public', 'themes')) if File.exist?(Rails.root.join('public', 'themes'))
          ::Refinery::Setting.set(:current_theme, params[:key])

          Rails.application.config.assets.prepend Refinery::Themes::Theme.theme_path.join("assets/fonts").to_s
          Rails.application.config.assets.prepend Refinery::Themes::Theme.theme_path.join("assets/javascripts").to_s
          Rails.application.config.assets.prepend Refinery::Themes::Theme.theme_path.join("assets/stylesheets").to_s
          Rails.application.config.assets.prepend Refinery::Themes::Theme.theme_path.join("assets/images").to_s
          #Rake::Task['assets:precompile'].invoke

          ::I18n.load_path += Dir[Refinery::Themes::Theme.theme_path.join('config', 'locales', '*.{rb,yml}').to_s]

          redirect_to themes_admin_root_url
        end

        def create
          zipf = params[:zip_file]

          directory = "/tmp/uploads"
          `rm -rf "#{directory}"`
          `mkdir "#{directory}"`

          path = File.join(directory, zipf.original_filename)
          File.open(path, "wb") { |f| f.write(zipf.read) }

          FileManager.unzip_theme(path)
          `rm #{path}`

          redirect_to themes_admin_root_url, :notice =>"A new theme was successfully uploaded and installed!"
        end

      end
    end
  end
end

app/controllers/refinery/themes/theme_controller.rb
module Refinery
  module Themes
    class ThemeController < ::ApplicationController

      skip_before_action :verify_authenticity_token

      def screenshot
        send_data IO.read(File.join(Refinery::Themes::Theme.theme_path(params[:key]), "config/image.png")),
                  :disposition => "inline", :stream => false
      end

      def asset
        file_path = File.join(Refinery::Themes::Theme.theme_path, "assets", params[:mime_type], "#{params[:file_path]}.#{params[:format]}")

        if File.exists? file_path
          #file_type = Mime::Type.lookup_by_extension(File.extname(file_path)[1..-1])
          send_file file_path,  :disposition => "inline", :stream => false
        else
          render :nothing => true, :status => 404
        end
      end
    end
  end
end

app/helpers/themes/application_helper.rb
module Themes
  module ApplicationHelper
  end
end

app/views/refinery/themes/admin/themes/index.html.erb
<%= render :partial => "refinery/themes/admin/shared/theme_assets" %>
<%= render "refinery/themes/admin/shared/actions" %>

<div id='records'>
    <% if @themes.any? %>
        <% current_theme = Refinery::Themes::Theme.current_theme_config %>
        <table cellpadding="1" cellspacing="1" style="width: 100%; ">
            <tbody>
            <tr>
                <td style="width: 70%">
                    <%= link_to(image_tag("/themes/#{current_theme['config']['key']}/image.png",
                                          {class: 'screenshot'}), "/themes/#{current_theme['config']['key']}/image.png",
                                {class: 'fancybox', title: 'Preview Theme'}) %>
                </td>
                <td class="theme-info">
                    <h1><%= current_theme['config']['name'] %><br><span>ver. <%= current_theme['config']['version'] %></span></h1>
                    <span>by <%= current_theme['config']['author'] %></span>

                    <p><%= current_theme['config']['description'] %></p>
                    <% if current_theme['config']['key'].eql?('default') %>
                        <p>
                            <%= link_to t('refinery.themes.admin.themes.actions.reset'), '#',
                                        :onclick => "Themes.resetToDefaultTheme('#{refinery.reset_themes_admin_themes_path}')",
                                        :class => 'button' %>
                        </p>
                    <% end %>
                </td>
            </tr>

            <% @themes.reject { |i| i['config'].eql?(current_theme['config']) }.each do |theme| %>
                <tr>
                    <td style="width: 70%">
                        <%= link_to(image_tag("/themes/#{theme['config']['key']}/image.png", {class: 'screenshot'}), "/themes/#{theme['config']['key']}/image.png",
                                    {class: 'fancybox', title: 'Preview Theme'}) %>
                    </td>
                    <td class="theme-info">
                        <h1><%= theme['config']['name'] %><br><span>ver. <%= theme['config']['version'] %></span></h1>
                        <span>by <%= theme['config']['author'] %></span>
                        <p><%= theme['config']['description'] %></p>

                        <p><%= link_to "Select Theme", "/refinery/themes/select_theme?key=#{theme['config']['key']}", {class: "button select_theme_button"} %>
                            <%= image_tag "spinner.gif", :style => "display:none", :id => 'spinner', :class => "spinner" %>
                        </p>
                        <% if theme['config']['key'].eql?('default') %>
                            <p>
                                <%= link_to t('refinery.themes.admin.themes.actions.reset'), '#',
                                            :onclick => "Themes.resetToDefaultTheme('#{refinery.reset_themes_admin_themes_path}')",
                                            :class => 'button' %>
                            </p>
                        <% end %>
                        <!--<p><%= link_to "Preview Theme", "/themes/#{theme['config']['key']}/image.png", class: "fancybox button" %></p>-->
                    </td>
                </tr>
            <% end %>
            </tbody>
        </table>
    <% end %>
</div>

app/views/refinery/themes/admin/themes/upload.html.erb
<%= render :partial => "refinery/themes/admin/shared/theme_assets" %>
<%= render "refinery/themes/admin/shared/actions" %>

<section class="clearfix one_list" id="records">
    <%= form_tag(themes_admin_themes_path, :multipart => true) do |f| %>
        <div class='field'>
            <label for="zip_file">ZIP File:</label>
            <%= file_field_tag 'zip_file', class: 'widest' %>
        </div>
        <div class="form-actions">
            <div class="form-actions-right"><%= submit_tag "Upload" %></div>
        </div>
    <% end %>
</section>