config/routes.rb
Rails.application.routes.prepend  do
  get "/themes/:key/image.png", :to => "refinery/themes/theme#screenshot"
  get "/themes/assets/:mime_type/*file_path", :to => "refinery/themes/theme#asset"
end

Refinery::Core::Engine.routes.prepend do
  # Admin routes
  namespace :themes, :path => '' do
    namespace :admin, :path => 'refinery' do
      scope :path => 'themes' do
        resource :editor, :controller => 'editor' do
          member do
            get :index
          end

          collection do
            post :list
            post :file
            post :save_file
            post :add
            post :rename
            post :delete
            post :upload
            get  :upload_file
          end
        end
      end


      resources :themes, :except => [:show, :destroy, :new] do
        collection do
          get :upload
          get :reset
          get :settings
          get :select_theme
        end
      end

    end
  end

end

app/controllers/refinery/themes/admin/editor_controller.rb
module Refinery
  module Themes
    module Admin
      class EditorController < ::Refinery::AdminController

        def index; end

        def upload_file
          @path = params[:path]
        end

        def upload
          file = params[:file]

          unless FileManager.allowed_content_type?(File.extname(file.original_filename))
            notice = 'File "%s" could not be uploaded' % File.extname(file.original_filename)
          else
            file_path = "#{params[:path]}/#{file.original_filename}"
            FileManager.save_file(file_path, file.read)
            notice = "A new file was successfully uploaded!"
          end
          @dialog_successful = true
          render :nothing => true, :layout => 'refinery/admin_dialog'
          #render :action => 'index'
          #redirect_to(refinery.root_themes_admin_editor_path, :notice => notice)
        end

        def list
          @parent = params[:fullpath]
          file_manager = FileManager.new(Rails.root.join("themes/#{Refinery::Themes::Theme.current_theme_key}/#{@parent}"), @parent)
          render :json => file_manager.dirs.concat(file_manager.files), :layout => false
        end

        def file
          @related_path = params[:fullpath]
          file = File.join(Rails.root, "themes", Refinery::Themes::Theme.current_theme_key, params[:fullpath])
          render :text => 'file not found' and return unless File.exist? file
          @content = File.read(file)
          @content_type = Editable.mime_for file

          if @content_type == 'image'
            render :inline => "<%= image_tag '#{params[:fullpath]}' %>"
          else
            render :layout => false
          end
        end

        def save_file
          @related_path = params[:file_name]
          @content = FileManager.save_file(@related_path, params[:file_content])
          @content_type = Editable.mime_for @related_path
          render :template => 'refinery/themes/admin/editor/file.html.erb', :layout => false
        end

        def add
          render(:json => FileManager.create_dir(params[:fullpath], params[:title]), :layout => false) if params[:type].eql?('folder')
          render(:json => FileManager.create_file(params[:fullpath], params[:title]), :layout => false) if params[:type].eql?('default')
        end

        def rename
          render(:json => FileManager.rename_dir(params[:fullpath], params[:new_name]), :layout => false) if params[:type].eql?('folder')
          render(:json => FileManager.rename_file(params[:fullpath], params[:new_name]), :layout => false) if params[:type].eql?('default')
        end

        def delete
          render(:json => FileManager.remove_dir(params[:fullpath]), :layout => false) if params[:type].eql?('folder')
          render(:json => FileManager.remove_file(params[:fullpath]), :layout => false) if params[:type].eql?('default')
        end

      end
    end
  end
end

app/views/refinery/themes/admin/editor/_editor_actions.html.erb
<% content_for :actions do %>
    <div class="mmenu">
        <input type="button" class="button" id="refresh" value="Refresh"/>
        <input type="button" class="button" id="add_folder" value="Add Root Folder"/>
    </div>
    <br>

    <div id="jsTree" class="jsTree jstree-apple"></div>
<% end %>

app/views/refinery/themes/admin/editor/file.html.erb
<div class="form-actions">
    <div class="form-actions-left">
        <a href="javascript:CodeMirrorManager.autoFormatSelection()" class="button">Autoformat</a>
        <a href="javascript:CodeMirrorManager.commentSelection(true)" class="button">Comment</a>
        <a href="javascript:CodeMirrorManager.commentSelection(false)" class="button">Uncomment</a>
    </div>
    <div class="form-actions-right">
        Select a theme:
        <select onchange="CodeMirrorManager.selectTheme()" id=select>
            <option selected>default</option>
            <option>ambiance</option>
            <option>blackboard</option>
            <option>cobalt</option>
            <option>eclipse</option>
            <option>elegant</option>
            <option>erlang-dark</option>
            <option>lesser-dark</option>
            <option>monokai</option>
            <option>neat</option>
            <option>night</option>
            <option>rubyblue</option>
            <option>solarized dark</option>
            <option>solarized light</option>
            <option>twilight</option>
            <option>vibrant-ink</option>
            <option>xq-dark</option>
        </select>
    </div>
</div>

<textarea cols="20" rows="20" id="editor"><%= raw @content %></textarea>
<form method="post" id="form_for_file" enctype="multipart/form-data" class="edit_file"
      action="<%= save_file_themes_admin_editor_url %>" accept-charset="UTF-8">
    <div style="margin: 0pt; padding: 0pt; display: inline;">
        <input type="hidden" value="✓" name="utf8">
        <input type="hidden" value="<%= @related_path %>" name="file_name">
        <input type="hidden" id="file_content" name="file_content">
        <%= token_tag(nil) %>
    </div>
</form>

<div class="form-actions">
    <div class="form-actions-right">
        <%= image_tag "spinner.gif", :style => "display:none", :id => 'spinner', :class => "spinner" %>
        <input class="button" type="submit" value="Save" name="commit" id="file_submit">
    </div>
</div>

<!--<iframe id=preview></iframe>-->
<%= javascript_tag "var codeMirrorManager = new CodeMirrorManager('editor', '#{@content_type}');" %>

app/views/refinery/themes/admin/editor/index.html.erb
<%= render :partial => "refinery/themes/admin/shared/theme_assets" %>
<%= render 'editor_actions' %>
<%= render "refinery/themes/admin/shared/actions" %>

<% content_for :javascripts do %>
    <%= javascript_include_tag "/assets/editor" %>
<% end %>
<% content_for :stylesheets do %>
    <%= stylesheet_link_tag '/assets/editor' %>
<% end %>

<section class="clearfix one_list" id='records'>
  <div class="fullwidth" id="code"><h2>Select any file from tree...</h2></div>
</section>

app/views/refinery/themes/admin/editor/upload_file.html.erb
<%= render :partial => "refinery/themes/admin/shared/theme_assets" %>
<section class="clearfix one_list" id="records">
    <%= form_tag(upload_themes_admin_editor_path, :multipart => true) do |f| %>
        <%= hidden_field_tag 'path', @path %>
        <div class='field'>
            <label for="file">Select File:</label>
            <%= file_field_tag 'file', class: 'widest' %>
        </div>
        <div class="form-actions">
            <div class="form-actions-right"><%= submit_tag "Upload" %></div>
        </div>
    <% end %>
</section>